#image: docker.artifactory-extern.dataport.de/node:16
image: tmaier/docker-compose:latest
#image: docker.artifactory-extern.dataport.de/docker:19.03.0-dind

stages:
  - build
  - test

# services:
#   - docker:dind

variables:
  http_proxy: "http://10.61.16.6:3128"
  https_proxy: "http://10.61.16.6:3128"
  NO_PROXY: "git.dataport.de,sonarqube.dataport.de,127.0.0.1,minio.gitlab-runner-minio.svc.cluster.local,al.s3.dataport.de,docker:2375,docker:2376,artifactory-extern.dataport.de,localhost:80"
  ARTIFACT_ROOT: "dchatbot-docker-development.artifactory-extern.dataport.de"
  IMAGE_PATH: "/conplat/cci/endtoendtests"
  CONTAINER_NAME: "cci-frontend"
  TAG_LATEST: $CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  TAGNAME: cci-e2e
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_URL: "docker.artifactory-extern.dataport.de"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm

before_script:
  # docker informations
#  - docker info
  # Setup SSH deploy keys
  # - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  # - eval $(ssh-agent -s)
  # - echo "$SSH_PRIVATE
  # - '[[ -f /.do&& echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  # - docker stack rm $tag_latest
  # - docker login -u $CONPLAT_ARTIFACTORY_USER -p $CONPLAT_ARTIFACTORY_PASS $ARTIFACT_ROOT
  # - docker-compose up -d

buildJob:
  #image: common-redhat-docker-development.artifactory-extern.dataport.de/ubi8/buildah
  stage: build
  before_script:
  - docker login -u $CONPLAT_ARTIFACTORY_USER -p $CONPLAT_ARTIFACTORY_PASS $ARTIFACT_ROOT
  #- docker-compose up -d
  script:
  - docker login -u $CONPLAT_ARTIFACTORY_USER -p $CONPLAT_ARTIFACTORY_PASS $ARTIFACT_ROOT
  - docker build -t $ARTIFACT_ROOT$IMAGE_PATH .
  #- docker push $ARTIFACT_ROOT$IMAGE_PATH
  - buildsh push --creds $CONPLAT_ARTIFACTORY_USER:$CONPLAT_ARTIFACTORY_PASS $ARTIFACT_ROOT$IMAGE_PATH
  #only:
  #  - merge_requests
  #  - schedules
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "schedule"'
  #     when: always

testJob:
  image: dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/endtoendtests
  stage: test
  #image: docker.artifactory-extern.dataport.de/cimg/node:16.13-browsers
  before_script:
    - docker login -u $CONPLAT_ARTIFACTORY_USER -p $CONPLAT_ARTIFACTORY_PASS $ARTIFACT_ROOT$IMAGE_PATH 
    #- docker pull $ARTIFACT_ROOT$IMAGE_PATH ;
    #- docker-compose up -d
  script:
    #- npm config set proxy $http_proxy
    #- npm config get proxy
    #- npm config set https-proxy $http_proxy
    #- npm set registry https://artifactory-extern.dataport.de:443/artifactory/api/npm/common-npm-central-development
    #- npm init -y
    - npm install cypress
    - npm install 
    - npm run CyTest
    # - docker stop myContainer && docker rm myContainer
    # - docker run -t -d -P -v pwd:/app --name myContainer $tag_latest
    # - docker cp myContainer:/app/cypress/results/junit/