image: tmaier/docker-compose:latest

services:
  - docker:dind

variables:
  TAG_LATEST: $CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  tag_latest: cabo:latest


before_script:
  # docker informations
  - docker info
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE
  - '[[ -f /.do&& echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - docker stack rm $tag_latest

buildJob:
  stage: build
  tags:
  - docker
  script:
  - docker build -t $tag_latest .
  #only:
  #- merge_requests
  #  - schedules
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "schedule"'
  #     when: always

testJob:
  stage: test
  tags:
  - docker
  script:
  - docker stop myContainer && docker rm myContainer
  - docker run -t -d -P -v pwd:/app --name myContainer $tag_latest
  - docker cp myContainer:/app/cypress/results/junit/