version: "3"
services:
  backend:
    image: dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/backend
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=test
    # extra_hosts:
    #   - 'local.machine:172.14.1.1'
  frontend:
    image: dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/frontend
    # extra_hosts:
    #   - 'local.machine:172.14.1.1'
  e2etest:
    build: .