version: "3.3"
services:
  backend:
    network_mode: host
    image: dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/backend
    environment:
      - envTarget=test    
  frontend:
    network_mode: host
    image: dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/frontend
  testEnv:
    network_mode: host
    image: dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/endtoendtests