version: "3.9"

services:
  proxy-e2e: 
    image: "docker.artifactory-extern.dataport.de/nginx:mainline"
    ports:
      - "8081:80"
    volumes:
      - /home/redakt/deployment_e2e/src/deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  frontend-e2e:
    image: "dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/frontend-distroless:latest"
  backend-e2e:
    image: "dchatbot-docker-development.artifactory-extern.dataport.de/conplat/cci/backend-distroless:latest"
    environment:
      - spring.profiles.active=e2e
      - chatbot.model.path=/app/models
      - keycloak.url=http://10.61.135.11:8081/auth/realms/dataport
    volumes:
      - /home/redakt/deployment_e2e/models:/app/models